apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nodeapp
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nodeapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodeapp
    spec:
      containers:
        - image: bejenar/nodeapp:<tag_version>
          name: nodeapp
          ports:
            - containerPort: 3000